### PR TITLE
feat(gyro/navx): implement NavX IMU

### PR DESCRIPTION
**Pull request by Baconing**

### CODE REVIEW

**Review by Trip-kun — APPROVED** [review]
Looks good to me. I didn't look at the other gyro code, just make sure the offset matches what is expected from other gyros (so if the offset is in degrees, you're all good, if it's in radians, then you scale the offset, etc.)
If NavX sim exists, try to use it.

**Comment by Trip-kun** [comment]
Note: cannot merge this because of the bad gpg. 
Also, if you can, fix the github actions, they've been broken for a while.

**Comment by Baconing** [comment]
> Looks good to me. I didn't look at the other gyro code, just make sure the offset matches what is expected from other gyros (so if the offset is in degrees, you're all good, if it's in radians, then you scale the offset, etc.) If NavX sim exists, try to use it.

No NavX sim exists, and offset is calculated using degrees 💯

**Comment by Trip-kun** [comment]
It does exist: See the following
https://www.chiefdelphi.com/t/navx-mxp-gyro-simulation-in-java/405419/2

**Pull request merged**
